# Generated by Django 5.0.6 on 2024-07-02 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='visiting_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visiting_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.city'),
        ),
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.ManyToManyField(to='dashboard.image'),
        ),
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='propID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='dashboard.property'),
        ),
        migrations.AddField(
            model_name='town',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towns', to='dashboard.city'),
        ),
        migrations.AddField(
            model_name='property',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.town'),
        ),
    ]
